version: '3'
services:
  tendergo-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1401:1433"
    networks:
     - tendergo-network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
    volumes:
      - tendergo-sql-data:/var/opt/mssql
   
  tendergo-rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tendergo-network

  tendergo-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=tendergo-sql;Database=${DB_NAME};User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True
      - RabbitMQ__Host=tendergo-rabbitmq
      - RabbitMQ__Username=${RABBITMQ_USER}
      - RabbitMQ__Password=${RABBITMQ_PASS}
    ports:
      - "8080:8080"
    depends_on:
      - tendergo-sql
      - tendergo-rabbitmq
    networks:
      - tendergo-network

  
   
networks:
  tendergo-network:
    driver: bridge

volumes:
  tendergo-sql-data: